name: Publish to npm
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org
    - run: npm install
    - run: make publish
      env:
        NPM_PUBLISH_TAG: ${{ github.ref }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
